version: "3.8"

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifidbcourse
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./queries/lab_08:/opt/nifi/nifi-current/userdata
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: appdbcourse
    command: python app.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgresdbcourse
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data/
      - ./dbdata:/dbdata
      - ./queries:/queries
    ports:
      - 5432:5432
