version: "3"

services:
  app:
    build:
      context: .
    container_name: dblab
    command: sh -c "python app.py"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
