version: "3.8"

services:
  app:
    build:
      context: .
    container_name: appdbcourse
    command: python app.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    container_name: postgresdbcourse
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
