#! /bin/bash

pylint $1 | tee pylint.txt
SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
echo -e "\e[1;33mYOUR \e[1;32mPYLINT\e[1;33m SCORE IS \e[1;32m$SCORE\e[0m\n"
rm pylint.txt